name: Auto Deploy Firebase
on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      # Deploy to Development Firebase Project
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          firebase use development --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only firestore:rules,firestore:indexes,database:rules --token "${{ secrets.FIREBASE_TOKEN }}"
          
      # Deploy to Production Firebase Project
      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        run: |
          firebase use production --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only firestore:rules,firestore:indexes,database:rules --token "${{ secrets.FIREBASE_TOKEN }}"
